export const GET_ERROR = "GET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";
export const USER_INFO_REQUEST = "USER_INFO_REQUEST";
export const USER_INFO = "GET_USER_INFO";
export const USER_INFO_SUCCESS = "USER_INFO_SUCCESS";
export const USER_INFO_FAILED = "USER_INFO_FAILED";

export const FORGOT_PASSWORD = "FORGOT_PASSWORD";

export const LOADING = "LOADING";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";

export const CART_CLEAR = "CART_CLEAR";
export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";

export const SELECT_SHIPPING_ADDRESS = "SELECT_SHIPPING_ADDRESS";
export const REMOVE_SHIPPING_ADDRESS = "REMOVE_SHIPPING_ADDRESS";
export const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS";
export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD";
export const SAVE_SHIPPING_ADDRESS_MAP_LOCATION =
  "SAVE_SHIPPING_ADDRESS_MAP_LOCATION";

export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_CART_ITEM = "UPDATE_CART_ITEM";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";

export const ADD_TO_FAVOURITE = "ADD_TO_FAVOURITE";
export const UPDATE_FAVOURITE = "UPDATE_FAVOURITE";
export const REMOVE_ITEM_FROM_FAVOURITES = "REMOVE_ITEM_FROM_FAVOURITES";

export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_FAIL = "GET_ORDER_FAIL";

export const PLACE_ORDER = "PLACE_ORDER";
export const GET_ORDER_HISTORY = "GET_ORDER_HISTORY";

export const GET_DASHBOARD_SUMMARY_REQUEST = "GET_DASHBOARD_SUMMARY_REQUEST";
export const GET_DASHBOARD_SUMMARY_SUCCESS = "GET_DASHBOARD_SUMMARY_SUCCESS";
export const GET_DASHBOARD_SUMMARY_FAILED = "GET_DASHBOARD_SUMMARY_FAILED";

export const ADD_NEW_PRODUCT_REQUEST = "ADD_NEW_PRODUCT_REQUEST";
export const ADD_NEW_PRODUCT_SUCCESS = "ADD_NEW_PRODUCT_SUCCESS";
export const ADD_NEW_PRODUCT_FAILED = "ADD_NEW_PRODUCT_FAILED";

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILED = "GET_PRODUCT_FAILED";

// coupon types
export const COUPON_REQUEST = "COUPON_REQUEST";
export const COUPON_FAILED = "COUPON_FAILED";

export const GET_COUPON_REQUEST = "GET_COUPON_REQUEST";
export const GET_COUPON_SUCCESS = "GET_COUPON_SUCCESS";
export const GET_COUPON_FAILED = "GET_COUPON_FAILED";

export const CREATE_COUPON_SUCCESS = "CREATE_COUPON_SUCCESS";
export const CREATE_COUPON_FAILED = "CREATE_COUPON_FAILED";
