export const GET_ERROR = "GET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";
export const USER_INFO = "GET_USER_INFO";

export const FORGOT_PASSWORD = "FORGOT_PASSWORD";

export const LOADING = "LOADING";

export const GET_CATEGORIES = "GET_CATEGORIES";

export const CART_CLEAR = "CART_CLEAR";
export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";

export const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS";
export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD";
export const SAVE_SHIPPING_ADDRESS_MAP_LOCATION =
  "SAVE_SHIPPING_ADDRESS_MAP_LOCATION";

export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_CART_ITEM = "UPDATE_CART_ITEM";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";

export const ADD_TO_FAVOURITE = "ADD_TO_FAVOURITE";
export const UPDATE_FAVOURITE = "UPDATE_FAVOURITE";
export const REMOVE_ITEM_FROM_FAVOURITES = "REMOVE_ITEM_FROM_FAVOURITES";
